// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace babble_model.Net.Sys
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "babble_model";





        [DllImport(__DllName, EntryPoint = "infer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ModelOutput infer(void/* byte[] */* left, void/* byte[] */* right);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ModelOutput
    {
        public float pitch_l;
        public float yaw_l;
        public float blink_l;
        public float pitch_r;
        public float yaw_r;
        public float blink_r;
    }



}
