// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace babble_model.Net.Sys
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "babble_model";





        [DllImport(__DllName, EntryPoint = "loadModel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ModelOutputResult loadModel(byte* path_ptr);

        [DllImport(__DllName, EntryPoint = "infer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ModelOutputResult infer(void/* byte[] */* left, void/* byte[] */* right);

        [DllImport(__DllName, EntryPoint = "freeModelOutputResult", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void freeModelOutputResult(ModelOutputResult result);

        [DllImport(__DllName, EntryPoint = "trainModel", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void trainModel(byte* usercal_path, byte* output_path, delegate* unmanaged[Cdecl]<TrainingDataCallback, void> cb);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ModelOutput
    {
        public float pitch_l;
        public float yaw_l;
        public float blink_l;
        public float eyebrow_l;
        public float eyewide_l;
        public float pitch_r;
        public float yaw_r;
        public float blink_r;
        public float eyebrow_r;
        public float eyewide_r;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ModelOutputResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool is_error;
        public ModelOutputValue value;
    }

    [StructLayout(LayoutKind.Explicit)]
    public unsafe partial struct ModelOutputValue
    {
        [FieldOffset(0)]
        public ModelOutput model_output;
        [FieldOffset(0)]
        public byte* error_message;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct TrainingDataCallback
    {
        public CallbackType callback_type;
        public int low;
        public int high;
        public float loss;
    }


    public enum CallbackType : byte
    {
        Batch = 0,
        Epoch = 1,
        Finished = 2,
    }


}
